### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by philn** [d-e-s-o/nitrocli#39]
Hi!

I'm trying nitrocli on macOS Mojave with my Nitrokey Storage, without success so far. All I get is:
```
$ nitrocli status
hidapi error: Device not found.
```

Is macOS supposed to be supported? I installed hidapi with brew and nitrocli with `cargo install`.

**Comment by robinkrahl** [comment]
I don’t have access to a Mac and @d-e-s-o has to decide whether macOS is a supported platform, but you should be able to run upcoming versions on a Mac.  Please try to compile the current development version from source by running:

```
$ git clone https://github.com/d-e-s-o/nitrocli
$ cd nitrocli
$ cargo build --release
$ ./target/release/nitrocli status
```

If you don’t want to install the development version, you’ll have to wait a few days until the next version is released.

**Comment by d-e-s-o** [comment]
Yeah, MacOS is currently unsupported (also see issue #1) and that is unlikely to change unless somebody with a Mac steps up to take over this part. I don't have one.

The "device not found" problem is also what I encountered back in the day when trying it out (again, issue #1). You can try with a more recent development snapshot as @robinkrahl 
 suggested. Since the "backend" library has changed there is a chance that this problem may have been fixed. If you try it out, please let us know your findings @philn.

**Comment by philn** [comment]
Thanks for the answers! Unfortunately libnitrokey doesn't seem to build with Apple's clang:
```
$ cargo run --release -- status
...
   Compiling nitrokey-sys v3.4.1 (/Users/phil/dev/rust/nitrocli/nitrokey-sys)                                                                                                                                                              
error: failed to run custom build command for `nitrokey-sys v3.4.1 (/Users/phil/dev/rust/nitrocli/nitrokey-sys)`                                                                                                                           
process didn't exit successfully: `/Users/phil/dev/rust/nitrocli/nitrocli/target/release/build/nitrokey-sys-2fea02ddcc4e2e43/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CXX_x86_64-apple-darwin = None
CXX_x86_64_apple_darwin = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-apple-darwin = None
CXXFLAGS_x86_64_apple_darwin = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libnitrokey-v3.4.1/libnitrokey" "-Wall" "-Wextra" "-o" "/Users/phil/dev/rust/nitrocli/nitrocli/target/release/build/nitrokey-sys-2b1e66ef680a387a/out/libnitrokey-v3.4.1/DeviceCommunicationExceptions.o" "-c" "libnitrokey-v3.4.1/DeviceCommunicationExceptions.cpp"
cargo:warning=In file included from libnitrokey-v3.4.1/DeviceCommunicationExceptions.cpp:22:
cargo:warning=libnitrokey-v3.4.1/libnitrokey/DeviceCommunicationExceptions.h:32:7: error: exception specification of overriding function is more lax than base version
cargo:warning=class DeviceCommunicationException: public std::runtime_error
cargo:warning=      ^
cargo:warning=libnitrokey-v3.4.1/libnitrokey/DeviceCommunicationExceptions.h:32:7: note: while declaring the implicit destructor for 'DeviceCommunicationException'
cargo:warning=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdexcept:106:13: note: overridden virtual function is here
cargo:warning=    virtual ~runtime_error() _NOEXCEPT;
cargo:warning=            ^
cargo:warning=libnitrokey-v3.4.1/DeviceCommunicationExceptions.cpp:24:55: error: expected ';' after top level declarator
cargo:warning=std::atomic_int DeviceCommunicationException::occurred {0};
cargo:warning=                                                      ^
cargo:warning=                                                      ;
cargo:warning=2 errors generated.
exit code: 1
```

**Comment by robinkrahl** [comment]
Which clang version do you use?  The libnitrokey builds on Xcode 8.2 (clang-800.0.42.1) and Xcode 9.1 (clang-900.0.38).  This seems to be an issue with newer clang versions.  Anyway, you should file an issue against the [upstream project](https://github.com/Nitrokey/libnitrokey).

**Comment by philn** [comment]
libnitrokey builds fine, CMake detected `AppleClang 10.0.0.10001145`. I'm a bit confused now :)

**Comment by philn** [comment]
Ah, `nitrokey-rs` doesn't build with C++14 enabled, I started a patch.

**Comment by robinkrahl** [comment]
From #42 :
> This only fixes the build, my device is still not detected.

Could you please try running the libnitrokey unit tests as described [here](https://github.com/nitrokey/libnitrokey#tests)?

**Comment by philn** [comment]
I'll check the unit tests tomorrow.
About https://git.ireas.org/nitrokey-sys-rs/commit/?h=next&id=a47058981611bacae464ed6deac39c6686357f3a I'm not sure it's correct to use `cfg!(target_os =...)` in build scripts. It might only be problematic when cross-compiling though. I'll double-check tomorrow!

**Comment by robinkrahl** [comment]
Okay, then it is an upstream issue.  Would you mind filing an issue against [the libnitrokey project](https://github.com/nitrokey/libnitrokey)?

**Comment by d-e-s-o** [comment]
`nitrokey-app` supports MacOS, right? Does it not use `libnitrokey` on it, too? I am a bit puzzled by this finding. Or is `nitrokey-app` still rolling its own logic everywhere (I believe it was doing so in the past, but that was quite some time ago; my details are a bit fuzzy on this front)?

**Comment by robinkrahl** [comment]
`nitrokey-app` uses `libnitrokey` (AFAIK since version 1.0) and macOS is listed as a supported platform in the README.  But I don’t know if it is tested regularly (except the automated unit tests).

**Comment by philn** [comment]
The `nitrokey-app` works fine for me on macOS and Debian. Sorry I should have clarified that earlier!

**Comment by robinkrahl** [comment]
That is really strange. @szszszsz Can you help us with this problem?

**Comment by szszszsz** [comment]
Hi!
Regarding macOS, direct cause lies in linking against `libhidapi` from brew. For Nitrokey App and `libnitrokey`, we use fixed [fork](https://github.com/nitrokey/hidapi) under Windows and macOS ([CMake](https://github.com/Nitrokey/libnitrokey/blob/master/CMakeLists.txt#L76-L80) [QMake](https://github.com/Nitrokey/libnitrokey/blob/master/libnitrokey.pro#L64-L67)). If you would find it handy, I can release it as a separate `hidapi` library (say `hidapi-nitrokey`; by moving proper make instructions there), installable to system. 
However, in case `nitrocli` would use already installed, system `libnitrokey` (which is built by default with the custom `hidapi`), the problem will probably go away, though asking user for installing it separately would probably not result in the best UX. Similar connection issue might occur under Windows.
Last time I have checked (and confirmed just now again), the original `hidapi` project is not maintained anymore, hence the need of fork.
Changes in the `hidapi-nitrokey` (against signal11's master, `mac` directory): [hidapi-nitrokey-diff.txt](https://github.com/d-e-s-o/nitrocli/files/2720296/hidapi-nitrokeyfork.txt)

**Comment by szszszsz** [comment]
Regarding C++ tests, these are not ready to use for the end-user yet, but rather used internally during the development, and are not device agnostic. `test1.cc` connects only to Nitrokey Pro, and `test2.cc` tests only Nitrokey Storage. I will: 
- [ ] add simple C++ connection tests for such cases like this one, and 
- [ ] describe the C++ tests state properly in the readme.

About release testing, each `libnitrokey` release is tested on supported platforms (Windows, macOS, Ubuntu/Fedora) using general Python tests with `pytest`, in `/unittest` directory:
- Pro: `pytest -v test_pro.py`
- Storage: `pytest -v test_pro.py && pytest -v test_storage.py`

Note: these require standard PINs set, and checks all features, including user data removal - please do not run it on production device.

Additionally, currently CI builds each pushed commit on macOS and Ubuntu: https://travis-ci.org/Nitrokey/libnitrokey

**Comment by robinkrahl** [comment]
Thank you for the explanation @szszszsz!  I agree that having a separate `hidapi-nitrokey` would be the ideal solution, but I’m not keen on maintaining something for a platform that I don’t have access to.  So for the time being, I’d suggest that macOS users install `libnitrokey` and then patch `nitrokey-sys` to use the pre-installed library.  Ideally, we find someone who is willing to maintain a Homebrew formula for `nitrocli` that would automate theses tasks.

But I still don’t understand why the unit tests failed for @philn.  As far as I see, he compiled `libnitrokey` from source, so it should have used the patched `libhidapi`, right?  Also, why does it fail on Debian?
.

**Comment by szszszsz** [comment]
@philn I have added a simple connection test as well to the `libnitrokey`'s master branch: `test_safe`. It contains only status check and will not change the data on the device any way. Will work on any device.
@robinkrahl You are welcome! Feel free to call me for support. I have macOS and could run tests periodically in case you would decide to support it. I will keep in mind releasing the `hidapi-nitrokey` then - let me know, if you would need it earlier. 

I am not experienced in Homebrew unfortunately, though we do have Nitrokey App buildable via `brew cask` already: https://github.com/Nitrokey/nitrokey-app/issues/291.

**Comment by szszszsz** [comment]
In Linux case, system wide `libhidapi` should be fine. Linking looks
alright.
1. Do you have `udev` rules in place (installed with the library)?
2. How about running `test_safe` with `sudo`?

**Comment by szszszsz** [comment]
Here is the culprit then :-) Hardware access for the user is regulated via the Udev service, and installation places the Udev rules file in your system. You can copy it manually, if you would like to, and it would work just as good.

**Comment by philn** [comment]
Yeah test_safe works now on my Debian box.

**Comment by robinkrahl** [comment]
@philn Did you mange to get test_safe to work under macOS?

**Comment by philn** [comment]
I haven't tried yet. Tonight maybe, sorry for the delay :)

**Comment by philn** [comment]
Also works on macOS! So what's left for this then? Seems like it all boils down to a bundling problem for nitrocli to use the right libnitrokey library.

**Comment by philn** [comment]
```
Running `target/release/nitrocli status`
dyld: Library not loaded: @rpath/libnitrokey.3.dylib
  Referenced from: /Users/phil/dev/rust/nitrocli/nitrocli/target/release/nitrocli
  Reason: image not found
```

I need to fiddle with otool it seems.

**Comment by robinkrahl** [comment]
Ah, you might have to set the `DYLD_LIBRARY_PATH` environment variable to the libnitrokey directory too (or install libnitrokey to the system library path).

**Comment by philn** [comment]
Oh sweet! It works now:
```
Status:
  model:             Storage
  serial number:     0x00050000
  firmware version:  0.52
  user retry count:  3
  admin retry count: 3

  SD card ID:        0x2484a9b6
  firmware:          unlocked
  storage keys:      created
  volumes:
    unencrypted:     active
    encrypted:       inactive
    hidden:          inactive
```

**Comment by d-e-s-o** [comment]
Awesome that we got that working!

@philn , all, can we close this issue? It appears all problems have been eliminated and `nitrocli` is working on Mac now. It also seems as if nothing needs to be fixed on the `nitrocli` side itself.

**Comment by philn** [comment]
Right, the problem is related with how to use the hidapi nitrokey fork from the Rust nitrokey bindings.

**Comment by robinkrahl** [comment]
@philn In `nitrokey-sys` v3.4.3, you can skip the build by setting the environment variable `USE_SYSTEM_LIBNITROKEY` when compiling.  So you don’t have to patch the source anymore with upcoming `nitrocli` versions.

@d-e-s-o Could you please update the bundled `nitrokey-sys` before the next release (but not the version requirement in `Cargo.toml` – we only need 3.4.*)?  And should we mention this workaround for macOS in the readme?

**Comment by d-e-s-o** [comment]
> @d-e-s-o Could you please update the bundled `nitrokey-sys` before the next release (but not the version requirement in `Cargo.toml` – we only need 3.4.* – Edit: `nitrokey-sys` obviously is a `nitrokey` dependency)?

Done.

> And should we mention this workaround for macOS in the readme?

We probably should :-)

**Comment by robinkrahl** [comment]
Thanks!  I’ll prepare a patch for the readme.
